# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-23 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_sessions', '0003_auto_20161205_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
